# Generated by Django 2.1.5 on 2019-01-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lancamentos',
            new_name='Lancamento',
        ),
    ]
